#PBS -N segmentation
#PBS -q autoai -l select=1:ncpus=16:mem=300gb:ngpus=2:gpu_model=a100,walltime=82:00:00
#PBS -o stdout.txt

module load anaconda3/2022.10-gcc/9.5.0 cuda/11.1.1-gcc/9.5.0 cudnn/8.0.5.39-11.1-gcc/9.5.0-cu11_1 openmpi/4.1.3-gcc/9.5.0-ucx gcc/9.5.0 mpfr/4.1.0-gcc/9.5.0

source activate vitAdapter

cd /scratch/ndang/OffRoadSemanticSegmentation/ViT-Adapter/segmentation/

sh dist_train.sh configs/loveDA/mask2former_beit_adapter_large_512_160k_loveda_ms.py 2